Update and rename build-claws-mail.yml to build-claws-mail-binary.yml

diff --git a/.github/workflows/build-claws-mail-binary.yml b/.github/workflows/build-claws-mail-binary.yml
--- a/.github/workflows/build-claws-mail-binary.yml
+++ b/.github/workflows/build-claws-mail-binary.yml
@@ -20,7 +20,7 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y \
             build-essential curl tar pkg-config \
-            git wget patchelf chrpath \
+            git wget patchelf \
             libetpan-dev libgnutls28-dev \
             libarchive-dev \
             ghostscript spamassassin \
@@ -109,7 +109,7 @@ jobs:
           echo "Before patchelf:"
           readelf -d ~/claws-mail-install/usr/bin/claws-mail | grep RPATH || echo "No RPATH set initially"
           ls -l ~/claws-mail-install/usr/bin/claws-mail
-          sudo patchelf --force-rpath --set-rpath \$ORIGIN/../lib ~/claws-mail-install/usr/bin/claws-mail --verbose || { echo "Patchelf failed"; exit 1; }
+          sudo patchelf --verbose --force-rpath --set-rpath \$ORIGIN/../lib ~/claws-mail-install/usr/bin/claws-mail || { echo "Patchelf failed"; exit 1; }
           echo "After patchelf:"
           readelf -d ~/claws-mail-install/usr/bin/claws-mail | grep RPATH || { echo "RPATH not set after patchelf"; exit 1; }
 
